text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Y'all Got Any More of Them
source: http://knowyourmeme.com/memes/yall-got-anymore-of
sample:
  - Y'ALL GOT ANY MORE OF THEM
  - MEMES
