text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Sarcastic Bear
sample:
  - I'M SO SORRY
  - I HAVEN'T MEMORIZED THE INTERNET
source: http://knowyourmeme.com/memes/sarcastic-bear
