text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Inigo Montoya
source: http://knowyourmeme.com/memes/you-keep-using-that-word-i-do-not-think-it-means-what-you-think-it-means
sample:
  - YOU KEEP USING THAT WORD
  - I DO NOT THINK IT MEANS WHAT YOU THINK IT MEANS
