text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: I Can Has Cheezburger?
sample:
  - I CAN HAS
  - THIS MEME?
source: http://knowyourmeme.com/memes/happy-cat
