name: Skeptical Snake
source: https://www.reddit.com/r/JoeRogan/comments/5kga5k/skeptical_snake/
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - WHEN YOU ALREADY CHECKED THAT ONE LEAF
  - AND IT STARTS MOVING
