text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Sweet Brown / Ain't Nobody Got Time For That
sample:
  - MEMES?
  - AIN'T NOBODY GOT TIME FO' THAT
source: https://knowyourmeme.com/memes/sweet-brown-aint-nobody-got-time-for-that
