text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Laundry Room Viking
source: http://knowyourmeme.com/memes/laundry-room-viking
sample:
  - DO THE LAUNDRY THEY SAID
  - IT WILL BE FUN THEY SAID
