text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: You Should Feel Bad
source: http://knowyourmeme.com/memes/your-musics-bad-and-you-should-feel-bad
sample:
  - YOUR MEME IS BAD
  - AND YOU SHOULD FEEL BAD
