name: Karate Kyle
source: https://knowyourmeme.com/memes/karate-kyle
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.15
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.85
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.15
example:
  - they broke my pencils
  - i broke their neck
styles:
  - luke
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
