name: Cheems
source: https://knowyourmeme.com/memes/cheems
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  - default
sample:
  - IT'S A GOOD TIME TO SLEEP
  - NOTHING WILL GO WRONG AFTER THIS
