text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Probably Not a Good Idea
source: https://www.youtube.com/watch?v=RFinNxS5KN4&t=86
sample:
  - YOU JUST WENT AND MADE A NEW DINOSAUR?
  - PROBABLY NOT A GOOD IDEA
