name: Probably Not a Good Idea
source: https://www.youtube.com/watch?v=RFinNxS5KN4&t=86
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  - default
sample:
  - YOU JUST WENT AND MADE A NEW DINOSAUR?
  - PROBABLY NOT A GOOD IDEA
