name: Life... Finds a Way
source: https://www.youtube.com/watch?v=dMjQ3hA9mEA
text:
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
styles:
  - default
sample:
  - LIFE...
  - FINDS A WAY
