site_name: Memegen.link
site_description: The free and open source API to generate memes.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/memegen
edit_uri: ""

nav:
  - Home: index.md
  - Examples: examples.md
  - Clients: clients.md

theme:
  name: mkdocs
  custom_dir: docs/theme
  nav_style: dark

plugins: []

google_analytics: ["UA-91304960-4", "memegen.link"]

remote_branch: site
