[tool.poetry]

name = "memegen-api"
version = "6.1"
description = "The open source meme generator."
authors = ["Jace Browning <jacebrowning@gmail.com>"]
license = "MIT"

packages = [ { include = "app" } ]

[tool.poetry.dependencies]

python = "^3.8"

# Sanic
sanic = "~20.6.3"
sanic-cors = "~0.10.0"
sanic-openapi = "~0.6.2"

# Utilities
aiohttp = "^3.6.2"
datafiles = "=0.11b4"
minilog = "^2.0b1"
pillow = "^7.1.1"
spongemock = "~0.3.4"

# Production
bugsnag = "*"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=5.5.1"
black = "=20.8b1"

# Type Checking
mypy = "~0.770"
autoflake = "^1.3.1"

# Testing
pytest = "^6.0"
pytest-asyncio = "*"
pytest-describe = { git = "https://github.com/pytest-dev/pytest-describe", rev = "9014bf3ee564518aad3622b5f035f7ca6139e398" }
pytest-expecter = "^2.1"
pytest-random = "*"
pytest-cov = "^2.7"

# Coverage
coveragespace = "^3.1.1"

# Utilities
ipdb = "*"
rope = "^0.14.0"
watchdog = { version = "*", extras = ["watchmedo"] }

[tool.black]

quiet = true

[tool.pytest.ini_options]

testpaths = "app"

addopts = """
--no-header --disable-warnings \
--random \
--cov=app --cov-report=term-missing:skip-covered --cov-report=html --no-cov-on-fail
"""

cache_dir = ".cache"

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
