[tool.poetry]

name = "memegen"
version = "0.0"
description = "The open source meme generator."
authors = ["Jace Browning <jacebrowning@gmail.com>"]
license = "MIT"

packages = [
    { include = "backend" },
]

[tool.poetry.dependencies]

python = "^3.7"

# Sanic
sanic = "^19.6.2"
sanic-openapi = "^0.5.3"

# Utilities
aiohttp = "^3.5"
datafiles = { git = "https://github.com/jacebrowning/datafiles", rev = "0bf54d92f6e63e16511bd2921299bb8a1a0ad75c" }

# Deployment
daphne = "^2.3"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=4.3.18"
black = "=19.3b0"

# Type Checking
mypy = "^0.701"

# Testing
pytest = "^5.0"
pytest-describe = "^0.12.0"
pytest-expecter = "^1.3"
pytest-cov = "^2.7"
pytest-watch = "^4.2"

# Coverage
coveragespace = "^2.1"

# Utilities
honcho = "^1.0"
gitman = { git = "https://github.com/jacebrowning/gitman", rev = "74b5e14fc42dbab635f41c218aee72980ab40361" }

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
