[tool.poetry]

name = "memegen"
version = "0.0"
description = "The open source meme generator."
authors = ["Jace Browning <jacebrowning@gmail.com>"]
license = "MIT"

packages = [
    { include = "backend" },
]

[tool.poetry.dependencies]

python = "^3.7"

# Sanic
sanic = "~19.12.2"
sanic-openapi = "=0.6.0"

# Utilities
aiohttp = "^3.5"
datafiles = "~0.9b2"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=4.3.21"
black = "=19.10b0"

# Type Checking
mypy = "~0.770"
autoflake = "^1.3.1"

# Testing
pytest = "^5.0"
pytest-describe = { git = "https://github.com/jacebrowning/pytest-describe", branch = "pytest-5.4-support" } # https://github.com/ropez/pytest-describe/pull/27
pytest-expecter = "^2.1"
pytest-cov = "^2.7"
pytest-watch = "^4.2"

# Coverage
coveragespace = "^3.1.1"

# Utilities
honcho = "^1.0"
gitman = "=2.0a3"
rope = "^0.14.0"

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
