[tool.poetry]

name = "memegen"
version = "0.0.0"
description = "The open source meme generator."
authors = ["Jace Browning <jacebrowning@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]

python = "^3.7"

sanic = "^19.3"
sanic-openapi = "^0.5.3"

datafiles = "^0.4b2"

[tool.poetry.dev-dependencies]

isort = "=4.3.18"
black = "=19.3b0"

mypy = "^0.701.0"

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
