name: No Take, Only Throw
source: https://knowyourmeme.com/memes/no-take-only-throw
text:
  - color: black
    style: default
    anchor_x: 0.055
    anchor_y: 0.08
    angle: 12.0
    scale_x: 0.21
    scale_y: 0.15
  - color: black
    style: default
    anchor_x: 0.46
    anchor_y: 0.15
    angle: -0.01
    scale_x: 0.18
    scale_y: 0.15
  - color: black
    style: upper
    anchor_x: 0.7
    anchor_y: 0.135
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.15
styles:
  -
example:
  - Pls throw??
  - NO TAKE!!
  - ONLY THROW
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
