text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Xzibit Yo Dawg
source: http://knowyourmeme.com/memes/xzibit-yo-dawg
sample:
  - YO DAWG
  - I HEARD YOU LIKE MEMES
