text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Stop It, Get Some Help
source: https://knowyourmeme.com/memes/stop-it-get-some-help
sample:
  - STOP IT
  - GET SOME HELP
