name: Do You Want Ants?
source: http://knowyourmeme.com/memes/do-you-want-ants
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - do you want ants?
  - because that's how you get ants
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
