text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: That Would Be Great
source: http://knowyourmeme.com/memes/that-would-be-great
sample:
  - YEAH...
  - THAT'D BE GREAT
