name: Mocking Spongebob
source: http://knowyourmeme.com/memes/mocking-spongebob
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - style: mock
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
example:
  - "BF: I don't even know her like that"
  - "Me: i DoN'T eVeN KnOw HeR lIkE tHaT"
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
