name: Mocking Spongebob
source: http://knowyourmeme.com/memes/mocking-spongebob
text:
  - color: white
    style: none
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: mock
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
sample:
  - "BF: I don't even know her like that"
  - "Me: i DoN'T eVeN KnOw HeR lIkE tHaT"
