text:
  - color: white
    style: none
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    style: mock
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Mocking Spongebob
source: http://knowyourmeme.com/memes/mocking-spongebob
sample:
  - "BF: I don't even know her like that"
  - "Me: i DoN'T eVeN KnOw HeR lIkE tHaT"
