name: Error
source:
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - style: upper
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
styles:
  -
example:
  - your text
  - goes here
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
