name: Error
source:
text:
  - color: white
    style: upper
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
styles:
  -
example:
  - YOUR TEXT
  - GOES HERE
