version: 2

jobs:
  build:
    working_directory: ~/memegen-v2

    docker:
      - image: circleci/python:3.8.2-node-browsers

    steps:
      - checkout

      - run:
          name: Checking System Dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{{ checksum "poetry.lock" }}

      - run:
          name: Installing Project Dependencies
          command: make install

      - type: cache-save
        key: poetry-{{ checksum "poetry.lock" }}
        paths:
          - .venv

      - run:
          name: Checking Code
          command: make check

      - run:
          name: Running Tests
          command: make test
