text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: An Older Code Sir, But It Checks Out
sample:
  - IT'S AN OLDER MEME SIR
  - BUT IT CHECKS OUT
source: http://knowyourmeme.com/memes/its-an-older-meme-but-it-checks-out
