name: Oprah You Get a Car
source: http://knowyourmeme.com/memes/oprah-you-get-a-car
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
sample:
  - YOU GET A MEME
  - AND YOU GET A MEME
