text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Oprah You Get a Car
source: http://knowyourmeme.com/memes/oprah-you-get-a-car
sample:
  - YOU GET A MEME
  - AND YOU GET A MEME
