text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Hide the Pain Harold
sample:
  - WHEN THE BOSS SEES
  - YOUR MEME TAB
source: https://knowyourmeme.com/memes/hide-the-pain-harold
