name: Disaster Girl
source: http://knowyourmeme.com/memes/disaster-girl
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - what did you say?
  - ''
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
