text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Shut Up and Take My Money!
source: http://knowyourmeme.com/memes/shut-up-and-take-my-money
sample:
  - SHUT UP AND
  - TAKE MY MONEY!
