text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Nothing To Do Here
sample:
  - NOTHING TO DO HERE
source: http://knowyourmeme.com/memes/nothing-to-do-here-jet-pack-guy
