text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: I Should Not Have Said That
sample:
  - ''
  - I SHOULD NOT HAVE SAID THAT
source: https://www.youtube.com/watch?v=498HkRM77gg
