text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Socially Awesome Awkward Penguin
sample:
  - FIRST DAY AT NEW JOB
  - SPILL COFFEE ON BOSSMAN
source: http://knowyourmeme.com/memes/socially-awkward-penguin
