text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Push it somewhere else Patrick
sample:
  - WHY DONT WE TAKE ALL THE MEMES
  - AND PUT THEM ON MEMEGEN
source: http://knowyourmeme.com/memes/push-it-somewhere-else-patrick
