text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: So I Got That Goin' For Me, Which is Nice
source: http://knowyourmeme.com/memes/so-i-got-that-goin-for-me-which-is-nice
sample:
  - ''
  - SO I GOT THAT GOIN' FOR ME, WHICH IS NICE
