text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: I'm Going to Build My Own Theme Park
sample:
  - I'M GOING TO BUILD MY OWN THEME PARK
  - WITH BLACKJACK AND HOOKERS
source: http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
