name: I'm Going to Build My Own Theme Park
source: http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - I'M GOING TO BUILD MY OWN THEME PARK
  - WITH BLACKJACK AND HOOKERS
