name: I Have No Idea What I'm Doing
source: http://knowyourmeme.com/memes/i-have-no-idea-what-i-m-doing
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - i have no idea
  - what i'm doing
