text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: I Have No Idea What I'm Doing
source: http://knowyourmeme.com/memes/i-have-no-idea-what-i-m-doing
sample:
  - I HAVE NO IDEA
  - WHAT I'M DOING
