name: I Have No Idea What I'm Doing
source: http://knowyourmeme.com/memes/i-have-no-idea-what-i-m-doing
text:
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
styles:
  - default
sample:
  - I HAVE NO IDEA
  - WHAT I'M DOING
