text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Captain Hindsight
source: http://knowyourmeme.com/memes/captain-hindsight
sample:
  - IF YOU WANTED TO AVOID THE FRIEND ZONE
  - YOU SHOULD HAVE MADE YOUR INTENTIONS KNOWN FROM THE START
