text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: You Sit on a Throne of Lies
source: http://knowyourmeme.com/memes/you-sit-on-a-throne-of-lies
sample:
  - ''
  - YOU SIT ON A THRONE OF LIES
