text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Sad John Boehner
source: https://en.wikipedia.org/wiki/John_Boehner
sample:
  - SAD JOHN BOEHNER
  - DOESN'T THINK YOU'LL VOTE
