text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Sad Bill Clinton
source: https://en.wikipedia.org/wiki/Bill_Clinton
sample:
  - SAD BILL CLINTON
  - DOESN'T THINK YOU'LL VOTE
