text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Oh, Is That What We're Going to Do Today?
source: https://www.imdb.com/title/tt0720046/
sample:
  - OH, IS THAT WHAT WE'RE GOING TO DO TODAY?
  - WE'RE GOING TO FIGHT?
