text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: The Rent Is Too Damn High
sample:
  - THE RENT IS
  - TOO DAMN HIGH
source: http://knowyourmeme.com/memes/the-rent-is-too-damn-high-jimmy-mcmillan
