text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Sad Barack Obama
source: http://knowyourmeme.com/memes/sad-joe-biden
sample:
  - SAD BARACK OBAMA
  - DOESN'T THINK YOU'LL VOTE
