name: Awkward Moment Seal
source: https://knowyourmeme.com/memes/awkward-moment-seal
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - when you're watching a movie
  - and your parents walk in at the sex scene
