name: Phoebe Teaching Joey
source: https://knowyourmeme.com/photos/1846826-phoebe-teaching-joey
text:
  - color: white
    style: none
    anchor_x: 0.0
    anchor_y: 0.175
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.5
    anchor_y: 0.175
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.0
    anchor_y: 0.425
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.5
    anchor_y: 0.425
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.0
    anchor_y: 0.675
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.5
    anchor_y: 0.675
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.0
    anchor_y: 0.925
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - color: white
    style: none
    anchor_x: 0.5
    anchor_y: 0.925
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
styles:
  - default
sample:
  - Cast it
  - Cast it
  - into
  - into
  - the fire
  - the fire
  - Cast it into the fire.
  - Keep the Ring of Power!
