name: What is this, a Center for Ants?!
source: http://knowyourmeme.com/memes/what-is-this-a-center-for-ants
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  - default
sample:
  - WHAT IS THIS
  - A CENTER FOR ANTS
