text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: So Hot Right Now
source: https://www.youtube.com/watch?v=QizsJQNIKhc
sample:
  - THIS MEME IS
  - SO HOT RIGHT NOW
