name: Daily Struggle
source_url: https://knowyourmeme.com/memes/daily-struggle
text:
- color: white
  anchor_x: 0.1
  anchor_y: 0.2
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.6
- color: white
  anchor_x: 0.1
  anchor_y: 0.2
  angle: 0.0
  scale_x: 0.5
  scale_y: 0.6
