text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.9
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: But That's None of My Business
source: http://knowyourmeme.com/memes/but-thats-none-of-my-business
sample:
  - ''
  - BUT THAT'S NONE OF MY BUSINESS
