text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Skeptical Third World Kid
sample:
  - YOU FINISHED YOUR PLATE
  - BECAUSE I WAS STARVING?
source: http://knowyourmeme.com/memes/third-world-success
