name: Skeptical Third World Kid
source: http://knowyourmeme.com/memes/third-world-success
text:
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
styles:
  - default
sample:
  - YOU FINISHED YOUR PLATE
  - BECAUSE I WAS STARVING?
