text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: Dating Site Murderer
sample:
  - THEY WILL NEVER FIND YOUR BODY
  - AS ATTRACTIVE AS I DO
source: http://knowyourmeme.com/memes/dating-site-murderer
