name: You Know What Really Grinds My Gears?
source: http://knowyourmeme.com/memes/you-know-what-really-grinds-my-gears
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - you know what really grinds my gears?
  - when people post images of cogs that don't mesh
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
