text:
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
  - color: white
    anchor_x: 0.1
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.8
    scale_y: 0.2
name: You Know What Really Grinds My Gears?
sample:
  - YOU KNOW WHAT REALLY GRINDS MY GEARS?
  - WHEN PEOPLE POST IMAGES OF COGS THAT DON'T MESH
source: http://knowyourmeme.com/memes/you-know-what-really-grinds-my-gears
