name: At Least You Tried
source: http://knowyourmeme.com/memes/you-tried
text:
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
styles:
  - default
sample:
  - AT LEAST
  - YOU TRIED
