name: I am the Captain Now
source: https://www.youtube.com/watch?v=dvA-mimf2yg
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
example:
  - LOOK AT ME
  - I AM THE CAPTAIN NOW
