text:
  - color: white
    anchor_x: 0.05
    anchor_y: 0.05
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
  - color: white
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
name: Butthurt Dweller
source: http://knowyourmeme.com/memes/butthurt-dweller-gordo-granudo
sample:
  - CAN'T WORKOUT
  - DON'T WANT TO GET TOO BUFF
