name: This is Fine
source: http://gunshowcomic.com/648
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
example:
  - ''
  - this is fine
styles:
  -
overlay:
  - center_x: 0.425
    center_y: 0.54
    scale: 0.5
